version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kuyapads_db
      POSTGRES_USER: kuyapads_user
      POSTGRES_PASSWORD: kuyapads_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kuyapads_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: kuyapads_db
      DB_USER: kuyapads_user
      DB_PASSWORD: kuyapads_password
      JWT_SECRET: dev_jwt_secret_key
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: http://localhost:3000
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - kuyapads_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres_data:

networks:
  kuyapads_network:
    driver: bridge