version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kuyapads_db
      POSTGRES_USER: kuyapads_user
      POSTGRES_PASSWORD: kuyapads_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - kuyapads_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: kuyapads_db
      DB_USER: kuyapads_user
      DB_PASSWORD: kuyapads_password
      JWT_SECRET: ${JWT_SECRET:-your_super_secure_jwt_secret_key_change_this_in_production}
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: http://localhost:3000
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - kuyapads_network
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - kuyapads_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  kuyapads_network:
    driver: bridge